export const mockMainData = {
  success: true,
  code: 0,
  msg: '성공',
  data: [
    {
      boardIdx: 2,
      categoryIdx: 2,
      stackList: ['Python'],
      title: '테스트 내용',
      detail: {
        location: '수원',
        number: 5,
        onOff: '오프라인',
        parts: ['프론트엔드'],
      },
      boardStatus: '모집중',
      writer: {
        userIdx: 2,
        profileImgIdx: 1,
        userName: '정답',
      },
      createdAt: '2022-02-27T21:52:50',
      watch: 3,
      heart: 0,
      totalComent: 1,
      isHeart: 'N',
    },
    {
      boardIdx: 3,
      categoryIdx: 2,
      stackList: ['Spring'],
      title: '테스트 22',
      detail: {
        location: '서울',
        number: 3,
        onOff: '오프라인',
        parts: ['백엔드'],
      },
      boardStatus: '모집중',
      writer: {
        userIdx: 2,
        profileImgIdx: 1,
        userName: '정답',
      },
      createdAt: '2022-03-01T19:53:46',
      watch: 3,
      heart: 0,
      totalComent: 0,
      isHeart: 'N',
    },
    {
      boardIdx: 5,
      categoryIdx: 2,
      stackList: ['React'],
      title: '임시 저장 제목 2',
      detail: {
        location: '수원',
        number: 5,
        onOff: '오프라인',
        parts: ['백엔드', '프론트엔드'],
      },
      boardStatus: '임시저장',
      writer: {
        userIdx: 1,
        profileImgIdx: 1,
        userName: 'team',
      },
      createdAt: '2022-03-02T23:59:08',
      watch: 0,
      heart: 0,
      totalComent: 0,
      isHeart: 'N',
    },
  ],
};
