export const mockMainData = {
  success: true,
  code: 0,
  msg: '성공',
  data: [
    {
      boardIdx: 3,
      categoryIdx: 2,
      stackList: ['Spring'],
      title: '테스트 22',
      detail: {
        location: '서울',
        number: 3,
        onOff: '오프라인',
        parts: ['백엔드'],
      },
      boardStatus: '모집중',
      writer: {
        userIdx: 2,
        profileImgIdx: 1,
        userName: '정답',
      },
      createdAt: '2022-03-02T13:58:14',
      watch: 17,
      heart: 0,
      totalComent: 0,
      isHeart: 'N',
    },
    {
      boardIdx: 2,
      categoryIdx: 2,
      stackList: ['Python'],
      title: '테스트 내용',
      detail: {
        location: '수원',
        number: 5,
        onOff: '오프라인',
        parts: ['프론트엔드'],
      },
      boardStatus: '모집중',
      writer: {
        userIdx: 2,
        profileImgIdx: 1,
        userName: '정답',
      },
      createdAt: '2022-02-27T21:52:50',
      watch: 10,
      heart: 1,
      totalComent: 1,
      isHeart: 'Y',
    },
    {
      boardIdx: 26,
      categoryIdx: 2,
      stackList: ['Node.js', 'TypeScript'],
      title: '모집중 test10',
      detail: {
        location: '인천',
        number: 4,
        onOff: '온라인',
        parts: ['백엔드', '프론트엔드'],
      },
      boardStatus: '모집중',
      writer: {
        userIdx: 1,
        profileImgIdx: 1,
        userName: 'team',
      },
      createdAt: '2022-03-19T19:50:55',
      watch: 9,
      heart: 0,
      totalComent: 0,
      isHeart: 'N',
    },
    {
      boardIdx: 25,
      categoryIdx: 2,
      stackList: ['C', 'TypeScript'],
      title: '모집중 test9',
      detail: {
        location: '서울',
        number: 3,
        onOff: '온라인',
        parts: ['ios개발자', '프론트엔드'],
      },
      boardStatus: '모집중',
      writer: {
        userIdx: 1,
        profileImgIdx: 1,
        userName: 'team',
      },
      createdAt: '2022-03-19T19:48:19',
      watch: 5,
      heart: 0,
      totalComent: 0,
      isHeart: 'N',
    },
    {
      boardIdx: 27,
      categoryIdx: 2,
      stackList: ['Node.js', 'TypeScript'],
      title: '모집중 test10',
      detail: {
        location: '인천',
        number: 4,
        onOff: '온라인',
        parts: ['백엔드', '프론트엔드'],
      },
      boardStatus: '모집중',
      writer: {
        userIdx: 1,
        profileImgIdx: 1,
        userName: 'team',
      },
      createdAt: '2022-03-21T22:39:06',
      watch: 0,
      heart: 0,
      totalComent: 0,
      isHeart: 'N',
    },
    {
      boardIdx: 24,
      categoryIdx: 2,
      stackList: ['Python'],
      title: '모집중 test8',
      detail: {
        location: '서울',
        number: 2,
        onOff: '온라인',
        parts: ['기획자', '프론트엔드'],
      },
      boardStatus: '모집중',
      writer: {
        userIdx: 1,
        profileImgIdx: 1,
        userName: 'team',
      },
      createdAt: '2022-03-19T19:45:15',
      watch: 0,
      heart: 0,
      totalComent: 0,
      isHeart: 'N',
    },
    {
      boardIdx: 23,
      categoryIdx: 2,
      stackList: ['C++'],
      title: '모집중 test7',
      detail: {
        location: '서울',
        number: 2,
        onOff: '온라인',
        parts: ['기획자', '프론트엔드'],
      },
      boardStatus: '모집중',
      writer: {
        userIdx: 1,
        profileImgIdx: 1,
        userName: 'team',
      },
      createdAt: '2022-03-19T19:44:57',
      watch: 0,
      heart: 0,
      totalComent: 0,
      isHeart: 'N',
    },
    {
      boardIdx: 22,
      categoryIdx: 2,
      stackList: ['Angular'],
      title: '모집중 test6',
      detail: {
        location: '서울',
        number: 5,
        onOff: '온라인',
        parts: ['기획자', '프론트엔드'],
      },
      boardStatus: '모집중',
      writer: {
        userIdx: 1,
        profileImgIdx: 1,
        userName: 'team',
      },
      createdAt: '2022-03-19T19:44:33',
      watch: 0,
      heart: 0,
      totalComent: 0,
      isHeart: 'N',
    },
  ],
};
